apiVersion: v1
kind: Secret
metadata:
  name: kubeinvaders-sa-token
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubeinvaders
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/service-account.name: kubeinvaders
type: kubernetes.io/service-account-token
