apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: kubeinvaders
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubeinvaders
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
