---
kind: Template
apiVersion: v1
metadata:
  name: kubeinvaders
  annotations:
    "openshift.io/display-name": Kubeinvaders
    description: Chaos Engineering Tool for Kubernetes and Openshift like SpaceInvaders but alien ships are pods
    iconClass: fa fa-cogs
    tags: "spaceinvaders"
parameters:
- description: URL of KubeInvaders
  name: ROUTE_URL
  value: kubeinvaders.local
- description: The location of the kubeinvaders image
  name: IMAGE_KUBEINVADERS
  value: docker.io/luckysideburn/kubeinvaders:latest
- description: The namespace to instantiate Kubeinvaders under.
  name: NAMESPACE
  value: kubeinvaders
- description: A namespaces to stress with KubeInvaders.
  name: TARGET_NAMESPACE
- description: Token of a serviceAccount that can kill PODs in specific namespace.
  name: TOKEN
- description: Openshift Master URL
  name: ENDPOINT
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: kubeinvaders
    namespace: ${NAMESPACE}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: kubeinvaders
    namespace: "${NAMESPACE}"
  spec:
    host: "${ROUTE_URL}"
    to:
      name: kubeinvaders
    tls:
      termination: Edge
- apiVersion: v1
  kind: Service
  metadata:
    name: kubeinvaders
    namespace: "${NAMESPACE}"
    labels:
      name: kubeinvaders
  spec:
    ports:
    - name: kubeinvaders
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: kubeinvaders
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: kubeinvaders
    namespace: "${NAMESPACE}"
  spec:
    replicas: 1
    selector:
       name: kubeinvaders
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: kubeinvaders
      spec:
        serviceAccountName: kubeinvaders
        containers:
        - env: 
          - name: NAMESPACE
            value: "${TARGET_NAMESPACE}"
          - name: TOKEN
            value: "${TOKEN}"
          - name: ENDPOINT
            value: "${ENDPOINT}"
          name: kubeinvaders
          image: "docker.io/luckysideburn/kubeinvaders:0.2.2"
          ports:
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ConfigChange
